    import { User } from "@prisma/client";
    import { useFetcher } from "@remix-run/react";
    import React from "react";
/**
 * 
 * @param postId @GPT generated by dev-kweku
 * @returns 
 */
    function usePostPeople(postId: number) {
    const [people, setPeople] = React.useState<User[]>([]);
    const fetcher = useFetcher<PeopleResponse>();

    React.useEffect(() => {
        fetcher.load(`/people?postId=${postId}`);
    }, [postId, fetcher]);

    React.useEffect(() => {
        if (fetcher.data?.people) {
        // Parse JSON dates into JavaScript Date objects
        const parsedPeople = fetcher.data.people.map((person) => ({
            ...person,
            createdAt: new Date(person.createdAt),
            updatedAt: new Date(person.updatedAt),
        }));
        setPeople(parsedPeople);
        }
    }, [fetcher.data]);

    return people;
    }

    interface UserResponse {
    id: number;
    username: string;
    email: string;
    createdAt: string; // Date as a string from JSON
    updatedAt: string; // Date as a string from JSON
    verified: boolean;
    role: string;
    bio: string | null;
    }

    interface PeopleResponse {
    people: UserResponse[];
    }

    export { usePostPeople };
